### ISSUE TITLE
HTML5 RTM materials not visible 

### ISSUE THREAD

**Issue by LTorrao** [Koderz/RuntimeMeshComponent#103]
I am deploying to HTML5 and materials that work on other meshes (non-RTM) aren't visible in RTM mesh, despite this not happening in non-HTML5 play.

I think I might have detected a possible reason, because materials with no textures/texture parameters do seem to function ok.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
