### ISSUE TITLE
Build error for Unreal 4.20

### ISSUE THREAD

**Issue by gamecoder-nz** [Koderz/RuntimeMeshComponent#106]
'UPrimitiveComponent::bGenerateOverlapEvents': cannot access private member declared in class 'UPrimitiveComponent'

It should use SetGenerateOverlapEvents

**Comment by Mattgahan** [comment]
Good fix. Worked for me.

**Comment by Loriborn** [comment]
Still receiving this error when trying to build, and thus am unable to build.
`2>C:\Users\user\Documents\Unreal Projects\Project\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\RuntimeMeshActor.cpp(18): error C2659: '=': function as left operand`

**Comment by guachitonico** [comment]
Thanks, worked like a charm.

**Comment by DivineChili** [comment]
Quick and easy fix, thx!

**Comment by Drezil** [comment]
this error should be fixed with https://github.com/Koderz/RuntimeMeshComponent/commit/6bee6c39694fd69d6195614b9dc739edcbc4aa87, so this issue could be closed, right?

or does this issue persist?
