### ISSUE TITLE
Shading Issue in 4.20

### ISSUE THREAD

**Issue by MaximeDup** [Koderz/RuntimeMeshComponent#107]
"Create Mesh Section" Ouput shading is corrupted in 4.20. Using the same input Vertices/Triangles/Normals/tangent/UV with ProceduralMeshComponent, which is working as expected, highlight the issue:

https://www.youtube.com/watch?v=QVApdH4gMfI

Wish i could use RuntimeMeshComponent properly on 4.20, the performance is just day and night compared to ProceduralMeshComponent. 

Is the 'extended' RuntimeMeshComponent fully working on 4.20? I'm ready to buy the plugin if needed.

**Comment by aeroson** [comment]
These two capsules looked the same in 4.19:
![image](https://user-images.githubusercontent.com/3437520/44837349-b5528e80-ac39-11e8-9e1c-9ca9a11655df.png)

With unlit material that outputs PixelNormalWS:
![image](https://user-images.githubusercontent.com/3437520/44837435-e92db400-ac39-11e8-9d52-600fd9bae852.png)

**Comment by rpajo** [comment]
Can confirm shading has been fixed

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
