### ISSUE TITLE
ARuntimeMeshActor Tick issue

### ISSUE THREAD

**Issue by JerryHyun** [Koderz/RuntimeMeshComponent#109]
Super::BeginPlay();

This code have to add in "void ARuntimeMeshActor::BeginPlay()" Function.

After, we can use Tick!!

**Comment by Kuldaen** [comment]
Pr #111 was merged

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
