### ISSUE TITLE
No collision in packaged game

### ISSUE THREAD

**Issue by HiIAmMoot** [Koderz/RuntimeMeshComponent#112]
This happened before with older versions(https://github.com/Koderz/RuntimeMeshComponent/issues/23), comment said to make a new issue for version 3.

The issue is exactly the same. I'm using 4.20 and I have no collision in a packaged game while I do have collision in the editor.

I have tried turning on async cooking but no luck. Both mesh collision and convex collision work in the editor but not in a packaged game.

**Comment by SizzleBae** [comment]
I am having the exact same problem, using 4.20

**Comment by BulleTime** [comment]
same here with 4.20.2!

**Comment by zhangchaorui** [comment]
Has anyone solved this problem？？？

**Comment by rpajo** [comment]
I have also had this problem, but solved it by setting "Use complex collision as simple" to false, by adding a convex collision hull, setting "Use async cooking" to true and "Cooking the collison". Don't know which step solved it but it's working now

**Comment by Moddingear** [comment]
Use Complex as Simple solves it, the others are optionnal.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
