### ISSUE TITLE
warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder'

### ISSUE THREAD

**Issue by stevenmessick** [Koderz/RuntimeMeshComponent#113]
I am seeing the following warnings when compiling the RuntimeMeshComponent plugin on Android:

RuntimeMeshBlueprintMeshBuilder.h(42,67) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(48,62) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(54,58) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(61,49) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(68,51) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(74,53) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(80,50) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(87,52) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(93,53) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(99,51) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(105,52) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(112,49) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(123,53) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(129,52) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(135,52) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(141,55) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(147,49) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(154,49) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(166,51) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(173,49) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(181,50) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(188,48) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(195,45) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(203,56) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(210,51) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(223,48) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(229,51) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(236,48) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]
RuntimeMeshBlueprintMeshBuilder.h(242,47) :  warning: declaration shadows a field of 'URuntimeBlueprintMeshBuilder' [-Wshadow]

This can be fixed by renaming the member variable "MeshBuilder" (TSharedPtr<FRuntimeMeshBuilder>) to "MyMeshBuilder". Unfortunately, changing the parameter name in the UNFUNCTIONs will break any existing blueprints.

**Comment by Kuldaen** [comment]
Fix merged in pr #115

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
