### ISSUE TITLE
Unrecognized type 'URuntimeBlueprintMeshBuilder'

### ISSUE THREAD

**Issue by AbsintheScripting** [Koderz/RuntimeMeshComponent#114]
When compiling in the editor, UnrealHeaderTool:
`.../Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMesh.h(345)  : Error: Unrecognized type 'URuntimeBlueprintMeshBuilder' - type must be a UCLASS, USTRUCT or UENUM`

this makes no sense, because URuntimeBlueprintMeshBuilder is a UCLASS and the header file is included

(Unreal Engine v4.20.1)

Visual Studio compiles it without errors

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
