### ISSUE TITLE
Shader expected a uniform buffer of struct type LocalVF

### ISSUE THREAD

**Issue by sh54** [Koderz/RuntimeMeshComponent#123]
I am getting the following error when trying to do anything with the runtime mesh component:

Fatal error: [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Commands.cpp] [Line: 1502] Shader expected a uniform buffer of struct type LocalVF at slot 3 but got null instead. Rendering code needs to set a valid uniform buffer for this slot.

UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:425]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::SetResourcesFromTables<FD3D11VertexShader>() [d:\build\++ue4\sync\engine\source\runtime\windows\d3d11rhi\private\d3d11commands.cpp:1500]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::CommitGraphicsResourceTables() [d:\build\++ue4\sync\engine\source\runtime\windows\d3d11rhi\private\d3d11commands.cpp:1557]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::RHIDrawIndexedPrimitive() [d:\build\++ue4\sync\engine\source\runtime\windows\d3d11rhi\private\d3d11commands.cpp:1662]
UE4Editor_Renderer!FMeshDrawingPolicy::DrawMesh() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\drawingpolicy.cpp:184]
UE4Editor_Renderer!FDrawBasePassDynamicMeshAction::Process<FUniformLightMapPolicy>() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\basepassrendering.cpp:507]
UE4Editor_Renderer!ProcessBasePassMesh<FDrawBasePassDynamicMeshAction>() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\basepassrendering.h:1268]
UE4Editor_Renderer!FBasePassOpaqueDrawingPolicyFactory::DrawDynamicMesh() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\basepassrendering.cpp:540]
UE4Editor_Renderer!FDeferredShadingSceneRenderer::RenderBasePassDynamicData() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\basepassrendering.cpp:1124]
UE4Editor_Renderer!FDeferredShadingSceneRenderer::RenderBasePass() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\basepassrendering.cpp:946]
UE4Editor_Renderer!FDeferredShadingSceneRenderer::Render() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\deferredshadingrenderer.cpp:977]
UE4Editor_Renderer!RenderViewFamily_RenderThread() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\scenerendering.cpp:2854]
UE4Editor_Renderer!TGraphTask<`FRendererModule::BeginRenderingViewFamily'::`33'::EURCMacro_FDrawSceneCommand>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:665]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:574]
UE4Editor_RenderCore!RenderingThreadMain() [d:\build\++ue4\sync\engine\source\runtime\rendercore\private\renderingthread.cpp:333]
UE4Editor_RenderCore!FRenderingThread::Run() [d:\build\++ue4\sync\engine\source\runtime\rendercore\private\renderingthread.cpp:467]
UE4Editor_Core!FRunnableThreadWin::Run() [d:\build\++ue4\sync\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:76]

This is with a laptop with a Quadro M1000M with up to date drivers, Windows 10, Unreal 4.20, latest RMC from source.

**Comment by sh54** [comment]
I just tried with 4.19 and it works. So it looks like a regression with Unreal...

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
