### ISSUE TITLE
Link Error (UE 4.21.1.0)

### ISSUE THREAD

**Issue by Tadinu** [Koderz/RuntimeMeshComponent#129]
Hi, I bumped with this error as loading the plugin with UE:

libUE4Editor-RuntimeMeshComponent.so: undefined symbol: _ZN21URuntimeMeshComponent21GetPhysicsTriMeshDataEP21FTriMeshCollisionDatab

Have you ever seen this?

Thank you, Koderz!

**Comment by RaceTheMaSe** [comment]
Exactly, here is a [PR](https://github.com/Koderz/RuntimeMeshComponent/pull/127) that addresses this issue
