### ISSUE TITLE
Instancing, loosing materials

### ISSUE THREAD

**Issue by TrionProg** [Koderz/RuntimeMeshComponent#130]
Hello. I am trying to make instancing. As I guess, each my actor should have RuntimeMeshComponent, but all have same RuntimeMesh. I have two types of actors:Storage, that initialize mesh(before all actions) and children, those have this code in constructor(Generated from BP):

```
runtime_mesh = CreateDefaultSubobject<URuntimeMeshComponent>(TEXT("RuntimeMesh"));
RootComponent = default_scene_root;
default_scene_root->CreationMethod = EComponentCreationMethod::Native;
runtime_mesh->CreationMethod = EComponentCreationMethod::Native;
runtime_mesh->AttachToComponent(default_scene_root, FAttachmentTransformRules::KeepRelativeTransform);
	if (!runtime_mesh->IsTemplate())
		runtime_mesh->BodyInstance.FixupData(runtime_mesh);
```

And in UserConstructionScript I assign RuntimeMesh to RMC of the Child
```
runtime_mesh->SetRuntimeMesh(storage->runtime_mesh->GetRuntimeMesh());
```

Also Child has the **event**, that modifies RMC, As I expect, all children and storage will be changed
```
...
runtime_mesh->UpdateMeshSection(0, Vertices, Triangles, Normals, TextureCoordinates, VertexColors, Tangents);
auto TheMaterial_Dyn = UMaterialInstanceDynamic::Create(TheMaterial, this);
		runtime_mesh->SetSectionMaterial(0, TheMaterial_Dyn);
```

And then I have strange results.
Case 1: RMC of storage has no materials, I make the child and then set material for RMC of storage in the editor. I expect, that child has material, but it has no the same.
Case 2: I set material for RMC of storage in editor and then make child. Child has no material and **different** address of RemoteMesh
**Case 3**: I set material of storage in UserConstructionScript  by C++
```
auto TheMaterial_Dyn = UMaterialInstanceDynamic::Create(TheMaterial, this);
		runtime_mesh->SetSectionMaterial(0, TheMaterial_Dyn);
```
and then I make child.. and the child has the material! It also has different address of RM then storage! Then I change material of storage in editor but material of child does not changes. When I call **event** of child, geometry and material changes for storage and children.

In all cases on **event** geometry changes for storage and children. In 1 and 2 I also change material of Child by editor or C++ and where is no effect for storage and others.

I do not know, how UE works, but I think, that RM should be shared data in shared smart pointer.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
