### ISSUE TITLE
CreateMeshSectionDualBuffer not working

### ISSUE THREAD

**Issue by davidjo** [Koderz/RuntimeMeshComponent#131]
CreateMeshSectionDualBuffer does not display anything since commit 5f9d1a5c - the vectors are not even highlighted in the editor when object placed in the editor.
I am able to reproduce this using the SimpleCubeActor from the ProceduralMeshDemos repo. Adding code to copy the generated positions to a separate array and the generated vertices with no positions to a separate array then replacing the CreateMeshSection with CreateMeshSectionDualBuffer nothing is displayed. Using the original Vertices array and CreateMeshSection the cube is displayed.
There are no compile errors or crashes using CreateMeshSectionDualBuffer - just nothing displayed.
I have done this with UE4 4.18.3 and 4.20.3.
Is this now deprecated functionality?

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
