### ISSUE TITLE
RuntimeMesh will support Raytracing ?

### ISSUE THREAD

**Issue by ReturnZero23** [Koderz/RuntimeMeshComponent#132]

**Comment by ReturnZero23** [comment]
Unreal Engine 4.22.0-preview support Raytracing，Will RuntimeMesh support ray tracing? Do you have a plan?😋

**Comment by christopheKohler** [comment]
We have tested the plugin under 4.23 and raytracing is not yet supported in RunTime Mesh component. I'm discussing with EPIC team, they propose to help for porting the plugin. I've also contacted Chris/Koderz to synchronize everyone.

**Comment by ReturnZero23** [comment]
I've solved it. I have modified RuntimeMesh to support Raytracing by referring to ProceduralMesh and StaticMesh.

**Comment by tommybear** [comment]
> 
> 
> I've solved it. I have modified RuntimeMesh to support Raytracing by referring to ProceduralMesh and StaticMesh.

Any chance you could point out your solution? I'm in the same situation. Thank you!
