### ISSUE TITLE
4.22 support?

### ISSUE THREAD

**Issue by ioflowstudios** [Koderz/RuntimeMeshComponent#133]
Hi Koderz,

Sorry to be a pain but it looks like 4.21 has changed a bunch of stuff that breaks RMC.

I asked on discord, FlossFarming reckons ShaderCore got merged into RenderCore?

I tried just removing ShaderCore from the build files but it just broke a whole bunch more...

Cheers,
ioFlow

**Comment by ioflowstudios** [comment]
Bit more info, it's 4.22 that has rearranged shader core.

4.21 still works if you move the compiler directive in RuntimeMeshComponent.cpp down to re-enable the trimesh functions...

**Comment by Handkor** [comment]
I haven't had much time myself to try it out but I can confirm the 4.22 Preview 1 that Shadercore and Rendercore were modified heavily and merged around.

I think we need to wait for an official migration guide to 4.22 at this point, I've had no success RMC to compile again.

**Comment by MaximeDup** [comment]
Been using RMC on 4.22 for a couple weeks, no issues. As suggested by another issue ticket, ProceduralMeshComponent was also updated and performs as well if not better on a number of tasks.

**Comment by ioflowstudios** [comment]
Hey maxime,

How did you solve the build problems with shadercore having been merged into rendercore?

(My kung is not fu enough to wrangle with compiling at that level...)

**Comment by rezemble** [comment]
for me conditionally adding `ShaderCore` as a dependency based on `#if UE_4_22_OR_LATER` seems to work fine, apart from that the version I have doesn't seem to be very compatible with 4.22

**Comment by stephendb** [comment]
Any chance this is going to be updated for 4.22 ?

**Comment by GlassBeaver** [comment]
I’ve made a PR a while ago that makes it 4.22 compliant: https://github.com/Koderz/RuntimeMeshComponent/pull/136

**Comment by stephendb** [comment]
> I’ve made a PR a while ago that makes it 4.22 compliant: #136

I saw it shortly after comment, thanks!

**Comment by MaLeVoLenT1** [comment]
I'm not sure I'm quite understanding is it fixed or is there some guide I could perhaps use to fix it for 4.2+

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
