### ISSUE TITLE
Procedural mesh with better performance

### ISSUE THREAD

**Issue by Tefel** [Koderz/RuntimeMeshComponent#134]
Hey, Koderz.
When I run test for 10k 52 triangles each I got much worse results when using RMC.
I though that using RMC guarantees performance gain, but I was mistaken.
Setup: https://i.imgur.com/TxNrPsn.png

I know measuring FPS makes not much sense sometimes but here:
RMC: 160fps
PMC: 230fps

Forward rendering is enabled.

Kind regards,
Tefel

**Comment by MaximeDup** [comment]
@Tefel could you try with collision 'on' ?

**Comment by MaximeDup** [comment]
On the topic, if you haven't checked it yet, procedural mesh component was once again updated with 4.22 and features async. collision cooking which was trully missing compared to RuntimeMesh. 
In my tests Procedural Mesh Component performs better moving forward.

**Comment by erikdubbelboer** [comment]
But does the 4.22 Procedural Mesh Component support mobile targets? This is the reason why I switched to RuntimeMesh.

**Comment by Tefel** [comment]
Ah thanks guys, I thought I am doing maybe something wrong, but yeah. If you want to create static worlds without live updates ISM or HISM is the best choice.

4.22 WOOOOOOOOOOW :D
But test was for 4.21, but it explains a lot of things.
I love support from Epic and caring about details :)

**Comment by StephenLucasKnutson** [comment]
For what its worth, I tried compared 4.22 performance of RMC vs PMC.
RMC 4.21  22fps
RMC 4.22 33fps
PMC 4.22 15fps

So I'm not sure RMC is dead yet.  YMMV.

**Comment by MaximeDup** [comment]
Think it really depends of your use case, in my tests PMC was also faster. Done on 4.22

**Comment by Tefel** [comment]
Exactly! It all depends on your the case. I agree that updating mesh rapidly when using collisions is slowing down PCM, then of course RMC shines and can be used.

* RMC - It is actually good when you have unique mesh where geometry changes runtime.
* PMC - For multiple instances of the same mesh or just simple rendering purposes PMC is winning there.

**Comment by FishOrBear** [comment]
So if the geometry is not updated,
Is PMC faster in 4.21?
@Tefel

**Comment by Koderz** [comment]
@FishOrBear  v4 is out at this point and while I haven't finished optimizing it and profiling it against the PMC, everything I've tested shows significantly better performance for many operations than the PMC.

Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
