### ISSUE TITLE
More section run ok?

### ISSUE THREAD

**Issue by coolgong2002** [Koderz/RuntimeMeshComponent#137]
I created my terrain use RuntimeMeshComponent and my terrain has more 100 section. so it is error! only in android phone device.

LoginId:be1634ea42b1cb1a79a081b91ae4d58a
EpicAccountId:31a1f55a9f99412a83328c610db309e4

Assertion failed: MeshVertexFactory && MeshVertexFactory->IsInitialized() [File:d:\build\++ue4\sync\engine\source\runtime\renderer\private\MobileBasePassRendering.h] [Line: 938]

UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:425]
UE4Editor_Renderer!TMobileBasePassDrawingPolicy<FUniformLightMapPolicy>::SetMeshRenderState() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.h:939]
UE4Editor_Renderer!FDrawMobileBasePassDynamicMeshAction::Process() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.cpp:486]
UE4Editor_Renderer!ProcessMobileBasePassMesh<FDrawMobileBasePassDynamicMeshAction>() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.h:1228]
UE4Editor_Renderer!FMobileBasePassOpaqueDrawingPolicyFactory::DrawDynamicMesh() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.cpp:510]
UE4Editor_Renderer!FMobileSceneRenderer::RenderMobileBasePassDynamicData() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.cpp:729]
UE4Editor_Renderer!FMobileSceneRenderer::RenderMobileBasePass() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobilebasepassrendering.cpp:1075]
UE4Editor_Renderer!FMobileSceneRenderer::Render() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\mobileshadingrenderer.cpp:291]
UE4Editor_Renderer!RenderViewFamily_RenderThread() [d:\build\++ue4\sync\engine\source\runtime\renderer\private\scenerendering.cpp:2854]
UE4Editor_Renderer!TGraphTask<`FRendererModule::BeginRenderingViewFamily'::`33'::EURCMacro_FDrawSceneCommand>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:665]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:574]
UE4Editor_RenderCore!RenderingThreadMain() [d:\build\++ue4\sync\engine\source\runtime\rendercore\private\renderingthread.cpp:333]
UE4Editor_RenderCore!FRenderingThread::Run() [d:\build\++ue4\sync\engine\source\runtime\rendercore\private\renderingthread.cpp:467]
UE4Editor_Core!FRunnableThreadWin::Run() [d:\build\++ue4\sync\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:76]

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
