### ISSUE TITLE
I compiled the error in ue4 4.21

### ISSUE THREAD

**Issue by fx133** [Koderz/RuntimeMeshComponent#142]
ubt error：failed to produce itemi:D:\UEProject\Test4.21\Plugin\RuntimeMeshComponent\Intermediate\Build\Win64\UE4Editor\Development\RuntimeMeshComponent\UE4Editor-RuntimeMeshComponent,lib

**Comment by JackMaDrinkCoffee** [comment]
The project are built with 4.22.So you know?

**Comment by FishOrBear** [comment]
me too.
help !!!

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
