### ISSUE TITLE
Build Errors with UE4.23.0

### ISSUE THREAD

**Issue by JackMaDrinkCoffee** [Koderz/RuntimeMeshComponent#144]
4.23 update its API ,there is no "UseEditorDepthTest".I cant find suitable function replace it.  Can you please supply a new solution of it?

**Comment by JackMaDrinkCoffee** [comment]
I ve solved the issue.  there are modifications of the engine ,Check the differences and get the right properties will help.

**Comment by gjckdanek** [comment]
> I ve solved the issue. there are modifications of the engine ,Check the differences and get the right properties will help.

What is right propertie instead of UseEditorDepthTest() ?

**Comment by NuLL3rr0r** [comment]
I wonder the same thing. @JackMaDrinkCoffee could you please elaborate?

**Comment by Zaratusa** [comment]
The correct one is `DrawsVelocity()`.

**Comment by NuLL3rr0r** [comment]
Exactly, I figured it out but forgot to mention it here https://github.com/VIDILabs/ImsvGraphVis/pull/5/commits/7a8b2b52c541666e0e639fbd6c839edce0058191

From

```
	PrimitiveUniformBuffer = CreatePrimitiveUniformBufferImmediate(
		GetLocalToWorld(), GetBounds(), GetLocalBounds(), true, UseEditorDepthTest());
```

To

```
	FBoxSphereBounds PreSkinnedLocalBounds;
	GetPreSkinnedLocalBounds(PreSkinnedLocalBounds);
	PrimitiveUniformBuffer = CreatePrimitiveUniformBufferImmediate(
		GetLocalToWorld(), GetBounds(), GetLocalBounds(), PreSkinnedLocalBounds, ReceivesDecals(), DrawsVelocity(), LpvBiasMultiplier);
```

**Comment by kfatehi** [comment]
This fork worked for me in 4.23 https://github.com/stefanseibert/RuntimeMeshComponent

**Comment by RumbleballTheReal** [comment]
> 
> 
> This fork worked for me in 4.23 https://github.com/stefanseibert/RuntimeMeshComponent

Seems to mostly work, but UpdateFrequency set to "Infrequent" does not render the mesh.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
