### ISSUE TITLE
Editor mode Cant save changes in the demo project!

### ISSUE THREAD

**Issue by JackMaDrinkCoffee** [Koderz/RuntimeMeshComponent#145]
Once I place a RuntimeMeshActor into level the Actor BP detected changes and the BP cant be saved , It drive me crazy.Its there something wrong with my actions? how can I use it correctlly? It would be much appriciate who can tell me ?

**Comment by matthewberends** [comment]
I am also facing a similar issue. Did you figure anything out?

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
