### ISSUE TITLE
Unable to compile UE4 project file

### ISSUE THREAD

**Issue by jithinkoluthara** [Koderz/RuntimeMeshComponent#149]
Hi,

I am receiving an error when the plugin is added to the UE4 project file: Could not be compiled. Try rebuilding from source manually. 

![image](https://user-images.githubusercontent.com/17424705/68182208-49974e80-ffbf-11e9-9c0f-f3456273dd64.png)

**Comment by bringrainfire** [comment]
You'll need to unzip the contents of this repo into the "Plugins" Folder as shown in the example project found here -> https://github.com/Koderz/RuntimeMeshComponent-Examples

**Comment by bringrainfire** [comment]
I was testing it out and it seems like the only way the project compiles is by using the example. Creating a new project(either c++ or blueprint) and slaping the source into a Plugins directory fails to compile. Not sure what's going on but its not limited to this plugin as I've tried others with the same results.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
