### ISSUE TITLE
UE4 4.23.1 UpdateFrequency Infrequent does not render

### ISSUE THREAD

**Issue by nganjehloo** [Koderz/RuntimeMeshComponent#151]
Hi all,

After addressing the compilation errors when building with 4.23.1 I noticed that infrequent updates cause the mesh not to render at all. Any ideas?

**Comment by SZwahl** [comment]
The mesh seems to render when selected in the world outliner. I'm glad I found out this is what caused it because I was going crazy :P.

(Using 4.24 via [https://github.com/Koderz/RuntimeMeshComponent/pull/150](this) fix)

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
