### ISSUE TITLE
4.24 support?

### ISSUE THREAD

**Issue by x-mz** [Koderz/RuntimeMeshComponent#155]
Unable to compile UE4 project file

**Comment by bphelan** [comment]
Until you get an official response there are at least 3 forks of this project that are aimed at 4.24:  https://github.com/Koderz/RuntimeMeshComponent/network

I haven't tested any of them (including my own, beyond compilation).

**Comment by Koderz** [comment]
Version 4 is up and running on 4.24 (Working on full support for at minimum 4.23+ but trying for as far back as 4.20)

Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
