### ISSUE TITLE
Current state of LOD support?

### ISSUE THREAD

**Issue by galman33** [Koderz/RuntimeMeshComponent#157]
I'd like to know what's the current state of LOD support on RuntimeMeshComponent? How do you use it? Can it automatically create the different LODs or do I have to create them on my own?

Keep up the good work!

**Comment by Unit2Ed** [comment]
As far as I know you need to create them yourself, but once you've done that they do work, including the dither transitions!

**Comment by galman33** [comment]
Thanks! After I generated the LODs, do you know how to use them with the
RuntimeMesjComponent? What's the API?

**Comment by Unit2Ed** [comment]
See `URuntimeMeshProvider::ConfigureLOD`. You need to fill in a `FRuntimeMeshLODProperties` for each LOD level, with the screensize that you want that LOD to activate at.

**Comment by Moddingear** [comment]
Join the discord, it'll make communications faster

**Comment by Koderz** [comment]
Version 4 has fully functional LOD for both static and dynamic path draw!

If you have any issues, feel free to report them again here!

-Koderz
