### ISSUE TITLE
Will GenerateTessellationIndexBuffer be re-added in a future version?

### ISSUE THREAD

**Issue by panzhiyi3** [Koderz/RuntimeMeshComponent#159]
Hi,
I used the ESectionUpdateFlags :: CalculateTessellationIndices flag in the previous commit to automatically create AdjacencyTriangles, but in the latest version, all logic was replaced with xxxProvider, and the library URuntimeMeshLibrary :: CalculateTangentsForMesh was removed. We have to support tessellation in other ways in the project, can you consider re-supporting these features in future versions?

**Comment by Moddingear** [comment]
Probably, and it would be added via a pass through provider. You could do it by copying the code from rmc v3 into a new provider just like the normal provider
