### ISSUE TITLE
Memory leak due to smart pointer circular reference

### ISSUE THREAD

**Issue by Unit2Ed** [Koderz/RuntimeMeshComponent#163]
When releasing `URuntimeObject` for garbage collection, it contains sub-objects with `TSharedPtr`/`TSharedRef` smart-pointers to each other, preventing them from being destroyed.

This results in the RHI buffers for `URuntimeMeshData` never being released, causing a catastrophic memory leak.

I've mapped out the smart-pointers, starting from `URuntimeMesh` using the watch window:
![image](https://user-images.githubusercontent.com/33684704/78803355-d1daaf00-79b6-11ea-8090-73a995007332.png)

You can see that `FRuntimeMeshData` and `FRuntimeMeshProviderProxy` are pointing to each other, and this circle is never broken during `URuntimeMesh::Initialize(nullptr)` or garbage collection.

I've hack-fixed this locally by clearing `BaseProvider` and `PreviousProvider` inside `URuntimeMesh::Initialize`, and implementing `URuntimeMeshProvider::BeginDestroy` to clear `URuntimeMeshProvider::Proxy`.

Found in revision 08789f5f4f0623906859c872c32ee56f9e1f819f.

**Comment by Moddingear** [comment]
Fixed in commit 37e9a46
