### ISSUE TITLE
Don't have BP node

### ISSUE THREAD

**Issue by Reuneh** [Koderz/RuntimeMeshComponent#165]
I watched the [tutorial](https://m.youtube.com/watch?v=HNB3_nNPa_8) and found that I don’t have
Blueprint node, RuntimeMesh-> Create Grid Mesh, Create Mesh Selection. in engine plugin enabled
Could you help me, pls
UE 4.24.3

**Comment by Koderz** [comment]
That tutorial is out of date with the current RMC. The RMC has substantially changed in its structure since then. I'm working on rewriting the documentation, but for now the best thing I can suggest is to look at the examples project with the RMC.
