### ISSUE TITLE
Dynamic Point lights with/around RMC 

### ISSUE THREAD

**Issue by ApurvH** [Koderz/RuntimeMeshComponent#178]
What I am trying to do:
Add a dynamic point-light next to RMC created wall. Check screenshot. X-Y-Z Gizmo represents the point light.

![BugInRMC - Copy](https://user-images.githubusercontent.com/31202449/83979875-2a82e580-a92f-11ea-8d88-1958269aea4b.png)

As you can see in the image above, a wooden horizontal plank, which is a static mesh component has a correct light reflection. BUT RMC wall (no material) has light only to left. (As if masked by XZ plane)

I will try to create a reproducible example. But if there is something obvious that I am missing please let me know.

Two more screenshots to represent the issue:
First image has a point light just above RMC. The only light reflected left to X-Z plane is visible
2nd image has a point above the Static Mesh Ground Image. It works correctly.

![Incorrectpointlight_i](https://user-images.githubusercontent.com/31202449/83980125-e55fb300-a930-11ea-96f4-095f9f9cd0c9.png)
![Incorrectpointlight_c](https://user-images.githubusercontent.com/31202449/83980126-e7297680-a930-11ea-8827-a955006d03bf.png)

**Comment by Moddingear** [comment]
You have misconfigured normals/tangents or UV.
