### ISSUE TITLE
Slicer issues

### ISSUE THREAD

**Issue by filipeuva** [Koderz/RuntimeMeshComponent#21]
Hey, 

First of all I want to thank you, this is exactly what I needed to implement some features.

I know I'm posting this on the wrong repo, but I found no other way to enter in contact with you.

Using the slicer I get a lot of errors when validating section vert num < 0, also caps do not work some times.

Other question, can the slicer be used with dual buffer sections ? Currently it doesn't work.

Thanks !

**Comment by Koderz** [comment]
Yeah, the slicer has been pretty buggy. I’m slowly working on updating it as I get time. I’d be interested to see what errors you get, and then when the caps don’t work for you. In theory it should work with dual buffer but I’m not sure what issues there are.  I’m also completely rewriting it for the next RMC version but that likely will be a couple months before that version is done so will try to at least fix the simple bugs before then.

**Comment by filipeuva** [comment]
Thanks for the quick reply, I'll try and get samples for you of the Slicer bugs, give me a couple of days to compile some sample data.

Some things I should've made explicit the first time, I'm not using a source build, just a game project, importing and using RuntimeMeshSlicer required me to add the prefix RUNTIMEMESHCOMPONENTSLICER_API to be able to reach SliceRuntimeMesh()

As such : 

`class RUNTIMEMESHCOMPONENTSLICER_API URuntimeMeshSlicer : public UBlueprintFunctionLibrary`

Meanwhile, trying to slice some DualBuffers produced the following crash :

```
Fatal error: [File:D:\Build\++UE4+Release-4.14+Compile\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11VertexDeclaration.cpp] [Line: 49] 
Unknown RHI vertex element type 0
```

the code I'm using to generate it just in case : 

```
MeshComponent->CreateMeshSectionDualBuffer(SectionIndex, ProceduralMeshData.Vertices, ProceduralMeshData.VertexData, ProceduralMeshData.Triangles, bCreateCollision);

if (bCreateCollision) {
						MeshComponent->AddCollisionConvexMesh(ProceduralMeshData.Vertices);
					}
```

Would really love to use them to slice as I also need fast position updates :)

**Comment by assumptionsoup** [comment]
Just to add another data point, I've just tried converting my project to RMC from ProceduralMesh.  

I'm using mesh copied from a StaticMeshComponent and I'm seeing a lot of `RuntimeMeshLog:Error: Section is not of legacy type.` errors.  I'm also seeing duplicate meshes on each slice. I suspect one side is getting sliced but the other side is remaining as is.  I'll do some further tests tomorrow.

As an aside, if you're planning on rewriting some of the slicing code, I wanted to mention that I'm not a fan of the SliceProceduralMesh signature, which RMC copies.  Since the function creates a new component (`OutOtherHalfProcMesh`) instead of taking it as an input, it's impossible to subclass the ProceduralMeshComponent and get slices back in the right class, unless you rewrite the slice function without out the component creation line.

Finally, thanks for writing this plugin!  It's really great that there's someone working on a better procedural mesh!  Without this work, I might be dead in the water on my current project and need to give up or switch to Unity.

**Comment by Koderz** [comment]
I'm kind of in the predicament right now that to fix half of this is easier to rewrite it... but rewriting it now would still mean rewriting it again onto the new RMC... Still investigating this and will try to fix the easier things and bugs but the bigger usability issues might remain until I push the next version.

Basically I was trying to maintain full backwards compat with the PMC, but I'm to the point now where I pretty much just want to take the leap, ignore backwards compat and redesign it to be far better for the future... Still working through some things before I actually rewrite the core.


@assumptionsoup Yeah, I had thought about the subclass problem.

**Comment by filipeuva** [comment]
Well if your feel like your reimplementation is superior I have no problem with waiting. In fact I would encourage you to do so as a fellow programmer :)

I also agree with @assumptionsoup , OtherSlice should be a provided instance, optionally only initialised if it's null.

I tried to create a SliceRuntimeMesh() for DualBuffers, the bug was that as DualBuffers have Positions not stored on the VertexBuffer it would always return as on the other side of the slice plane. I can send you my version if your interested, it doesn't slice properly though. Also I can still send you some SliceCap bugs if you still want me to.

**Comment by Koderz** [comment]
@filipeuva Yeah definitely let me know of what bugs you know about. I might try to fix some of them if they're quick and also just want to know about them in case I use parts of existing pieces.

**Comment by assumptionsoup** [comment]
Awesome, I'm glad you're aware of the subclass issue.  I'm happy whichever development path you take.  Eventually, I expect there will be something awesome here :)

**Comment by assumptionsoup** [comment]
Tested my issue some more.  It looks like the input RMC mesh is not getting sliced.  It looks like the other half gets sliced correctly.  Same with the collision meshes, I think they're correct.  I think only the original input mesh is incorrect.

Occasionally, it looks like the cap material gets applied to the original mesh.  Not sure if this is a mesh swap (cap mesh somehow copied the original mesh) or a material swap (cap material accidentally applied to input mesh).  I've been testing exclusively with `ERuntimeMeshSliceCapOption::CreateNewSectionForCap`

**Comment by filipeuva** [comment]
Sorry for the delay, yes the problems come with the cap generation normally, when slicing sometimes the original RuntimeMeshComponent receives the material passed as the Cap Material, sometimes the plane side doesn't return any vertex on the other side but will still create a RuntimeMesh. Didn't really debug cap generation.

My version for Dual Buffer slicing btw, https://gist.github.com/filipeuva/58a5f1377ecbeb2e2343e91ccb73081b , doesn't really work, though the collision mesh is sliced properly.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
