### ISSUE TITLE
Collision is not working in packaged game

### ISSUE THREAD

**Issue by pranav2w** [Koderz/RuntimeMeshComponent#23]
I am using this plugin.This is very useful plugin and working perfectly in editor.But when I am packaging game and run it collision does not generate.

Is there any solution for it?Where I am going wrong?

**Comment by Koderz** [comment]
Sorry about the late response.

What platform was this packaged for? Win/Linux/Mac should work fine. If you publish to mobile it might have cooking disabled.

**Comment by Fitz000** [comment]
Same.  Windows 64.  Players are falling through the floor.

**Comment by Fitz000** [comment]
@Koderz Hey, I'm just tagging you because I just now got my deadline day.  We're presenting something with our game on Tuesday so we're hoping we can fix this for build by Monday.  So any help and direction you can give us before then would be soooo sooo soo appreciated.

**Comment by Zinglish** [comment]
@Fitz000 How are you using the plugin? Are you aware that if you're attempting to procedurally generate collision for PhyX objects then it won't work? See this [Issue 24](https://github.com/Koderz/UE4RuntimeMeshComponent/issues/24).

Also, merely replying to this threads sends notifications if he's subscribed. Owners of the repo are automatically subbed once an issue is made. He has been really busy lately from what I've seen so it may take him some time to reply unfortunately.

**Comment by Koderz** [comment]
Yeah @Fitz000  You don't have to tag me for me to see these messages. I just usually don't have time to check them right when I see them and then end up forgetting about them.

Honestly collision should just work on windows and it's by far the most tested platform since that's what i work with pretty much exclusively right now. How are you installing the plugin? marketplace or github? if github what specific version is it?  What engine version are you using? Is it a standard build from Epic or a source build?   Can you post the entire log of running it once packaged? It's been working for me so not sure why it would fail.

**Comment by Fitz000** [comment]
Thanks for the info on notifications! :)

We've had it working in the past in our builds.  We started on 4.13 but are currently on 4.14.3

@Zinglish Sadly I cannot tell you at this moment, I'm not the one who grabbed this plug in or designed our levels but they taxed me with fixing it ;) ;)

@Koderz I am almost, just certain, that it's our defaultengine.ini file or something else in the config folders.  We've had this working in the past.  At one point though someone wanted the defaultEngine file on the svn ignore list so we did that, and then over time everyone had different defaultEngine files on their computers.

**Comment by Koderz** [comment]
@Fitz000  would it be possible to see the log for an execution of the game in the packaged state. If you can visually see everything then the RMC itself is probably setup correctly, so not sure what would be causing it without seeing if the log says anything.

**Comment by Fitz000** [comment]
Not too sure which logs you may want to see.
I set the build config to "debug game" then packaged for windows 64.  These are logs I found in 
"gamename\saved\logs"

and as I try to upload them github is telling me it wont accept... they're .txt damn it!

**Comment by Fitz000** [comment]
[log.txt](https://github.com/Koderz/UE4RuntimeMeshComponent/files/798405/log.txt)
[log2.txt](https://github.com/Koderz/UE4RuntimeMeshComponent/files/798406/log2.txt)

**Comment by Koderz** [comment]
I don't see anything out of the ordinary there worth of the RMC. Have you been able to get this working?

**Comment by srogee** [comment]
I was working on the same project as Fitz000 and this was a bug with UE4 that was fixed in 4.15. Meshes generated at runtime (whether they were using the ProceduralMeshComponent or RuntimeMeshComponent) did not have collisions until we updated to 4.15.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz

**Comment by mason-bially** [comment]
Hey I'm getting this same problem. Packaged game I fall through runtime generated collision meshes, in editor it works. I am using the `UE4.19_Support` branch code, installed from github today.
