### ISSUE TITLE
Crash on UE4.15.1 shipping build

### ISSUE THREAD

**Issue by Maskotti** [Koderz/RuntimeMeshComponent#38]
When launching a project packaged in UE 4.15.1 (shipping build), the executable crashes on startup with the following output (when trying to create a render thread):

Access violation - code c0000005 (first/second chance not available)

PFS_Win64_Shipping!FD3D11DynamicRHI::RHILockVertexBuffer()
PFS_Win64_Shipping!FDynamicRHI::LockVertexBuffer_RenderThread()
PFS_Win64_Shipping!FRuntimeMeshVertexBuffer<FRuntimeMeshVertexSimple>::SetData() [d:\projects\unreal\pfs\simulator\plugins\ue4runtimemeshcomponent-2.0\source\runtimemeshcomponent\public\runtimemeshrendering.h:78]
PFS_Win64_Shipping!FRuntimeMeshSectionProxy<FRuntimeMeshVertexSimple,0>::FinishCreate_RenderThread() [d:\projects\unreal\pfs\simulator\plugins\ue4runtimemeshcomponent-2.0\source\runtimemeshcomponent\public\runtimemeshsectionproxy.h:171]
PFS_Win64_Shipping!FRuntimeMeshSceneProxy::CreateSection_RenderThread() [d:\projects\unreal\pfs\simulator\plugins\ue4runtimemeshcomponent-2.0\source\runtimemeshcomponent\private\runtimemeshcomponent.cpp:107]
PFS_Win64_Shipping!TGraphTask<`URuntimeMeshComponent::CreateSectionInternal'::`18'::EURCMacro_FRuntimeMeshSectionCreate>::ExecuteTask() [c:\program files\epic games\ue_4.15\engine\source\runtime\core\public\async\taskgraphinterfaces.h:888]
PFS_Win64_Shipping!FNamedTaskThread::ProcessTasksNamedThread()
PFS_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit()
PFS_Win64_Shipping!RenderingThreadMain()
PFS_Win64_Shipping!FRenderingThread::Run()
PFS_Win64_Shipping!FRunnableThreadWin::Run()

AFAIK the project settings should be as instructed for Runtime Mesh Component.
Any ideas what can be possibly causing this crash or how to fix it? Everything works fine when playing on editor.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
