### ISSUE TITLE
Can i update mesh color every frame?what should i do?

### ISSUE THREAD

**Issue by linmeeka** [Koderz/RuntimeMeshComponent#39]
I want to update the mesh shape and its color every frame,i used the function CreateMeshSectionDualBuffer to update position every frame.
So,what should i do to update the mesh's color?
please help me,thanks a lot：）

**Comment by Zinglish** [comment]
This comes down to material and/or vertex coloring (which is applied in material) and has nothing to do with RMC.

**Comment by linmeeka** [comment]
Thanks for your reply.
So,i used the function SetMaterial(index,material) in the runtime,successfully i loaded material,but i can't add texture to the material.
here is my code
reliefMapTexture = ConstructorStatics.TextureFinder.Get();
terrainMaterial = ConstructorStatics.MaterialFinder.Get();
DynamicMaterial = UMaterialInstanceDynamic::Create(terrainMaterial, this);
DynamicMaterial->SetTextureParameterValue(FName("flexBaconTex"), reliefMapTexture);
RuntimeMesh->SetMaterial(0, DynamicMaterial);

the problem is ,i can just set the material,but can't change the texture.
what's the problem?please help me!
thanks!

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
