### ISSUE TITLE
Pathfinding not working in "Shipping" Build configuration.

### ISSUE THREAD

**Issue by stevencheatham** [Koderz/RuntimeMeshComponent#41]
Pathfinding not working in "Shipping" Build configuration.

**Comment by Zinglish** [comment]
Define not working

**Comment by Koderz** [comment]
@stevencheatham,  I've not had any problems so I'd have to see what you're doing to be able to help at all.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
