### ISSUE TITLE
Create an empty mesh section on packaged versions causes a crash

### ISSUE THREAD

**Issue by Moddingear** [Koderz/RuntimeMeshComponent#42]
As the title says : If you try to create a mesh section without any triangles on packaged version, the game will crash instantly, regardless of the settings you input in the node.

**Comment by Zinglish** [comment]
Can we see some code please?

**Comment by Moddingear** [comment]
Well, just add the Create mesh section and set all the arrays to empty.

**Comment by Koderz** [comment]
Yes it asserts out. Internally this version can't really handle empty sections.  It logs an error while you're in the editor.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
