### ISSUE TITLE
Editor Crash upon Creating RuntimeMeshTangent Array from Blueprint (4.15)

### ISSUE THREAD

**Issue by aslatas** [Koderz/RuntimeMeshComponent#45]
For context, as a quick prototype, I'm trying to take a static mesh component which has several sections, and simply copy it to a runtime mesh component. The blueprint callable function "copyRuntimeMeshFromStaticMeshComponent" works fine for this. 

I'm having trouble then accessing the mesh data - there's no function available in blueprint to get the runtime mesh section's say, vertices array. This makes it impossible for me to then update the mesh section, as I don't have a vertex array to feed it. I'm unsure if I'm misunderstanding something and there's an easy way to do this, if it's only possible in C++, or not intended at all.

To get around this, I'm using the "getSectionFromStaticMesh" function, which returns all the data I need. In Blueprint, I can store this to play with later. Excellent. 

The procedural mesh component version of this function works fine, but any attempt to use the RMC version (the one that returns a runtime mesh tangent array) crashes the editor. I've provided the error log for this below. 

Further, using the procedural mesh version of the function and then calculating normal/tangent data for a runtime mesh also crashes the editor, as does storing that data in a variable. Creating an array of Runtime Mesh Tangent by hand compiles without issue, but using that array to update the mesh crashes the editor.

I haven't been very rigorous in isolating this in C++ code, but it seems like the same sort of problem exists - using the getSectionFromStaticMesh function, calculating runtime mesh tangents, etc. compile but crash the editor when called. 

It seems to me that something is wrong in my case when generating or using the runtime mesh tangent struct. I'm inexperienced and so I may just be missing something simple here, but below is a log file and I'd be happy to provide anything else.

 ```
> LoginId:aa10e1ce48afc9f013628c99f8cfa81d
> EpicAccountId:15120b2127334ed59ea403fb350f2b2b
> 
> Assertion failed: UV1s && UV1s->Num() > CurrentPosition [File:d:\build\++portal+main+full\sync\localbuilds\plugintemp\hostproject\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshBuilder.h] [Line: 786] 



> KERNELBASE

> UE4Editor_Core
> UE4Editor_Core
> UE4Editor_Core
> UE4Editor_RuntimeMeshComponent!FRuntimeMeshComponentVerticesBuilder::GetUV() [d:\build\++portal+main+full\sync\localbuilds\plugintemp\hostproject\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshbuilder.h:787]
> UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::CalculateTangentsForMesh() [d:\build\++portal+main+full\sync\localbuilds\plugintemp\hostproject\plugins\runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:241]
> UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::CalculateTangentsForMesh() [d:\build\++portal+main+full\sync\localbuilds\plugintemp\hostproject\plugins\runtimemeshcomponent\source\runtimemeshcomponent\private\runtimemeshlibrary.cpp:328]
> UE4Editor_RuntimeMeshComponent!URuntimeMeshLibrary::execCalculateTangentsForMesh() [d:\build\++portal+main+full\sync\localbuilds\plugintemp\hostproject\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshlibrary.h:14]
> UE4Editor_CoreUObject
> UE4Editor_CoreUObject
> UE4Editor_CoreUObject
> UE4Editor_CoreUObject
> UE4Editor_CoreUObject
> UE4Editor_CoreUObject
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_UnrealEd
> UE4Editor_UnrealEd
> UE4Editor_UnrealEd
> UE4Editor_Kismet
> UE4Editor_Kismet
> UE4Editor_Kismet
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor_Core
> UE4Editor_Core
> UE4Editor_Core
> UE4Editor_Core
> user32
> user32
> UE4Editor_Core
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> kernel32
> ntdll
 ```

**Comment by rottenhuman** [comment]
This is important, I hope we get an answer, a fix or a solution.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
