### ISSUE TITLE
UE 4.15.2 Compile Error

### ISSUE THREAD

**Issue by mukund-dh** [Koderz/RuntimeMeshComponent#46]
Hey I get the following error when I try to compile this with UE 4.15.2:

 error C2504: 'TStructOpsTypeTraitsBase2': base class undefined

TStructOpsTypeTraitsBase2 is not a template	
Line 72, RuntimeMeshComponent.h

**Comment by hhyyrylainen** [comment]
I'm also getting build errors with 4.15.2. This is the error I'm getting:
```
[2/8] Compile Module.RuntimeMeshComponentEditor.cpp
In file included from /home/hhyyrylainen/Unreal/Thrive/Plugins/RuntimeMeshComponent/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/RuntimeMeshComponent/PCH.RuntimeMeshComponent.h:113:
In file included from /home/hhyyrylainen/Unreal/Thrive/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Private/RuntimeMeshComponentPluginPrivatePCH.h:12:
../../../Thrive/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshComponent.h:73:83: error: 
      base class has incomplete type
  ...: public TStructOpsTypeTraits<FRuntimeMeshComponentPrePhysicsTickFunction>
       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../Thrive/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshComponent.h:73:8: note: 
      definition of 'TStructOpsTypeTraits<FRuntimeMeshComponentPrePhysicsTickFunction>' is not complete
      until the closing '}'
struct TStructOpsTypeTraits<FRuntimeMeshComponentPrePhysicsTickFunction> : public TStructOpsTypeT...
       ^
1 error generated.

```

**Comment by hhyyrylainen** [comment]
I was able to fork and fix this: https://github.com/Revolutionary-Games/UE4RuntimeMeshComponent

I can create a pull request if that is a sufficient fix.

**Comment by Koderz** [comment]
And that's what I get for trying to rush through a 4.16 fix...   That's actually been upgraded for 4.16 but for some reason didn't think to preprocess switch the old version back in for previous engines.

**Comment by Koderz** [comment]
Hopefully that's fixed but don't have 4.15 installed atm so can't verify that.

**Comment by DanielDurys** [comment]
d:\unrealengine4\ue_4.15\engine\source\runtime\coreuobject\public\UObject/Class.h(662): error C2280: 'FRuntimeMeshComponentPrePhysicsTickFunction &FRuntimeMeshComponentPrePhysicsTickFunction::operator =(const FRuntimeMeshComponentPrePhysicsTickFunction &)': attempting to reference a deleted function
2>         D:\Unreal Projects\VoxelWorld\Plugins\RuntimeMeshComponent_V2.0_WithSlicer\Source\RuntimeMeshComponent\Public\RuntimeMeshComponent.h(69): note: compiler has generated 'FRuntimeMeshComponentPrePhysicsTickFunction::operator =' here
2>         d:\unrealengine4\ue_4.15\engine\source\runtime\coreuobject\public\UObject/Class.h(997): note: see reference to function template instantiation 'bool CopyOrNot<CPPSTRUCT>(CPPSTRUCT *,const CPPSTRUCT *,int32)' being compiled
2>                 with
2>                 [
2>                     CPPSTRUCT=FRuntimeMeshComponentPrePhysicsTickFunction
2>                 ]
2>         d:\unrealengine4\ue_4.15\engine\source\runtime\coreuobject\public\UObject/Class.h(996): note: while compiling class template member function 'bool UScriptStruct::TCppStructOps<FRuntimeMeshComponentPrePhysicsTickFunction>::Copy(void *,const void *,int32)'
2>         D:\Unreal Projects\VoxelWorld\Plugins\RuntimeMeshComponent_V2.0_WithSlicer\Intermediate\Build\Win64\UE4Editor\Inc\RuntimeMeshComponent\RuntimeMeshComponent.generated.cpp(115): note: see reference to class template instantiation 'UScriptStruct::TCppStructOps<FRuntimeMeshComponentPrePhysicsTickFunction>' being compiled

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
