### ISSUE TITLE
Error in URuntimeMeshLibrary::CalculateTangentsForMesh()

### ISSUE THREAD

**Issue by RPG3D** [Koderz/RuntimeMeshComponent#47]
Got wrong when I use the funtion calculate tangent for a mesh, and it works well in ProceduralMeshComponent. I installed the RMC from marketplace, not source code 
UE 4.15.2

Vertices :  [0] (1000.0f, 0.0f, -100.0f)
[1] (-1000.0, -1000.0f, -100.0f)
[2] (-1000.0, 1000.0f, -100.0f)
[3] (0.0f, 0.0f, 2000.0f)

Triangles:  0 2 1
0 1 3
1 2 3
2 0 3

UV : all is (0.0f, 0.0f) for the 4 vertices

**Comment by Koderz** [comment]
What are you getting as results? the internals of that function in PMC vs RMC is nearly identical except supporting the change in vertex structure.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
