### ISSUE TITLE
Missing Triangles with Packed Arrays on 4.16

### ISSUE THREAD

**Issue by thescratt** [Koderz/RuntimeMeshComponent#51]
Maybe a dumb question as this is still listed as a 4.15 plugin, but I wanted to know if this is a known issue atm., or if I should dig into the problem further...

I am using the latest branch, and creating packed arrays from data that previously worked with ProceduralMeshComponents.

The resultant mesh renders ok, but is missing a number of triangles, in a fairly regular pattern.

I am basically pumping the vertex data into an array like this, in a loop..

`            Vertices.Add(
                         FRuntimeMeshVertexSimple(
                                                  m_vNode[j].m_vPosition,
                                                  m_vNode[j].m_vNormal,
                                                  FRuntimeMeshTangent(0,0,1),
                                                  FColor(0,0,0),
                                                  m_vNode[j].m_fTexCoord
                                                  ));
        }`

Previously I was pushing the same vertex data to individual arrays thus..

`                for (unsigned int j=0; j<count; j++) {
                    Vertices.Add(m_vNode[j].m_vPosition);
                    Normals.Add(m_vNode[j].m_vNormal);
                    UV0.Add(m_vNode[j].m_fTexCoord);
                }`

The index data has not changed.

**Comment by Koderz** [comment]
Well that's new..  Any chance you'd show the rest of how you're building both vertices and indices?   Since it's just an array and the RMC just copies it around internally and never alters it I'm not sure why that would change anything.

**Comment by thescratt** [comment]
Thanks for your reply. And also, thanks for the work you have done on RMC.

The creation of the vertex data and the indices is not trivial, so probably not easy to share a good example here. It's some code of mine that's about 10 years old, and has moved from OpenGL on a Mac, through iOS and now into UE4. It's for procedural terrain generation. That being said, having been through porting this to UE4 and fixing winding orders and so on I am pretty sure the generation side is solid.

I was more concerned that some MACRO magic might be borking the copy operations with the Vertex format. I've noticed your other conversations here about custom vertex structures and being on discord. I was trying to simplify this over the weekend and ran into similar issues with custom vertex structures as MJLaukala. So some of your comments to him were helpful.

My question here was more about asking if there was a known issue on 4.16, which it seems there isn't. So I'll dig in a bit and let you know what I find, and comment back here.. even if it's my own stupid fault. =) If I get really stuck I'll ping you on discord. ;)

**Comment by Koderz** [comment]
I wont lie, that generic vertex is a cluster ****.   It's kind of morphed over time from something far simpler to that mess of templates/macros it is now.   The one I built for the new version is almost entirely macros, so while it's still pretty nasty, it at least generates a simple struct with no inheritance or templates or anything else so intellisense works far better with it, debugging is far easier (try to look at the position component of one of those in the debugger some time lol )  

Your example for building the vertices there is basically the same setup I've used time and again. So unless one of the utilities is breaking it somehow if you're using any of them, the RMC shouldn't be changing that when it passes through to the GPU.

**Comment by thescratt** [comment]
Seems this was a driver bug on my development machine. I have a somewhat "non-standard" dev machine for.. reasons. ;) But I was under the impression the Graphics drivers were stable. On a PC and a different Mac this issue doesn't present. Sorry for the confusion from my side.
