### ISSUE TITLE
RuntimeMesh Can support skeletal animation?

### ISSUE THREAD

**Issue by myluoxz** [Koderz/RuntimeMeshComponent#54]
request support skeletal animation ？

**Comment by luoxz** [comment]
ASkeletalMeshActor  ？

**Comment by Koderz** [comment]
Skeletal animation isn't a simple thing to support. It's something that's interesting but unfortunately there's a long list of things with a higher priority and I'm working with limited time right now so if I look into it, it won't be for quite a while.

**Comment by luoxz** [comment]
#43   Large model support ? When it can be updated?

**Comment by luoxz** [comment]
I modified the components in the construction of the hierarchical relationship between the model, the efficiency increased a lot, but still need your plug-in strong update, will have a large qualitative change

**Comment by luoxz** [comment]
RMC v3 ？

**Comment by Koderz** [comment]
It's not that it doesn't support it, it does. There's just some things the SMC does to optimize itself that aren't yet implemented in the RMC or aren't practical to do at runtime.  It should still get better in v3, but I can't guarantee a release date on that due to time constraints.

**Comment by luoxz** [comment]
RuntimeMesh support Triangle Strip? how to use Strip RuntimeMesh?  @Koderz

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
