### ISSUE TITLE
UpdateMeshSection: C2039 - TypeInfo not a member of FVector

### ISSUE THREAD

**Issue by ponpal** [Koderz/RuntimeMeshComponent#55]
I have created a RuntimeMeshComponent and a mesh section using CreateMeshSection. In the Tick function, I modify the vertices and try to update the mesh using 

`UpdateMeshSection(0, vertices);`

which yields the error below. I am using the plugin installed from the Marketplace, version 2.1. Any idea what the problem is? Updating by using ClearAllMeshSections and creating a new mesh section each tick works fine. 

`Info Compiling game modules for hot reload
Info Performing 3 actions (2 in parallel)
Info Distorted.cpp
Error c:\program files\epic games\ue_4.16\engine\plugins\marketplace\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshSection.h(542) : error C2039: 'TypeInfo': is not a member of 'FVector'
Error C:\Program Files\Epic Games\UE_4.16\Engine\Plugins\Marketplace\RuntimeMeshComponent\Intermediate\Build\Win64\UE4Editor\Inc\RuntimeMeshComponent\RuntimeMeshComponent.generated.h(11) : note: see declaration of 'FVector'
Error c:\program files\epic games\ue_4.16\engine\plugins\marketplace\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshSection.h(542) : note: while compiling class template member function 'const FRuntimeMeshVertexTypeInfo *FRuntimeMeshSection<VertexType>::GetVertexType(void) const'
Info         with
Info         [
Info             VertexType=FVector
Info         ]
Error C:\Program Files\Epic Games\UE_4.16\Engine\Source\Runtime\Core\Public\Templates/PointerIsConvertibleFromTo.h(18) : note: see reference to class template instantiation 'FRuntimeMeshSection<VertexType>' being compiled
Info         with
Info         [
Info             VertexType=FVector
Info         ]
Error C:\Program Files\Epic Games\UE_4.16\Engine\Source\Runtime\Core\Public\Templates/SharedPointer.h(536) : note: see reference to class template instantiation 'TPointerIsConvertibleFromTo<ObjectType,TSharedFromThis<ObjectType,0>>' being compiled
Info         with
Info         [
Info             ObjectType=FRuntimeMeshSection<FVector>
Info         ]
Error C:\Program Files\Epic Games\UE_4.16\Engine\Plugins\Marketplace\RuntimeMeshComponent\Source\RuntimeMeshComponent\Public\RuntimeMeshComponent.h(318) : note: see reference to class template instantiation 'TSharedPtr<FRuntimeMeshSection<VertexType>,0>' being compiled
Info         with
Info         [
Info             VertexType=FVector
Info         ]
Error C:\Dev\NewDist\Source\NewDist\Distorted.cpp(55) : note: see reference to function template instantiation 'void URuntimeMeshComponent::UpdateMeshSection<FVector>(int32,TArray<FVector,FDefaultAllocator> &,ESectionUpdateFlags)' being compiled
Error c:\program files\epic games\ue_4.16\engine\plugins\marketplace\runtimemeshcomponent\source\runtimemeshcomponent\public\RuntimeMeshSection.h(542) : error C2065: 'TypeInfo': undeclared identifier
Info ERROR: UBT ERROR: Failed to produce item: C:\Dev\NewDist\Binaries\Win64\UE4Editor-NewDist-6910.dll
Info Total build time: 19.76 seconds (Local executor: 0.00 seconds)
`

**Comment by Koderz** [comment]
Looks like you tried to pass a TArray<FVector> to UpdateMeshSection.   you either need to pass the packed vertex array if you're using them, or if you're using separate component arrays pass them as empty to use the correct function. That overload is meant for packed arrays, so it wont accept just a FVector array. 

Hope that helps!

**Comment by ponpal** [comment]
It did help, problem solved! 
Thanks!
