### ISSUE TITLE
Is it necessary to calculate Normals and Tangents when creating a mesh?

### ISSUE THREAD

**Issue by Yifan-opt** [Koderz/RuntimeMeshComponent#57]
Hi,

I am new to Unreal and use RMC for the first time. I want to create a cylinder mesh procedurally by using RMC. If I use the CreateMeshSection method, do I have to clarify the Normals and Tangents? I have created a cylinder mesh in Unity. In Unity, setting the vertices and triangles properly is enough to create the mesh. I wonder if there is a way to achieve that by using RMC? It seems that adding Normals and Tangents makes the work far more complicated.

Thanks!

**Comment by Koderz** [comment]
If you're using the version of CreateMeshSection that takes the multiple arrays (1 for position, 1 for normals, 1 for tangents etc)  then you can just pass an empty array to normal and tangent and it should work fine.

With that said, you won't be able to use normal mapping without those. There's a utility in URuntimeMeshLibrary  that can calculate them for you, be warned it's exponentially slower the larger the mesh you give it. I have a much faster version built that's coming in the next release.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
