### ISSUE TITLE
Collisions work in Play In Editor mode but not when using Launch or Packaging project

### ISSUE THREAD

**Issue by Reyitgex** [Koderz/RuntimeMeshComponent#58]
OS: Win64
Engine: 4.16.2
Project link: https://mega.nz/#!zdxw2DDQ!uHxHgButoB3K0LE59eLAOy5DOIwxlRJhh2bFJa4Bq7w

- Drag a Simple Cube Actor and my Actor_Blueprint into the scene.
- Play in editor, notice how the collisions work.
- Launch, notice how the collisions no longer work.

Will be happy to provide any more details if needed :)

**Comment by RaiaN** [comment]
@Reyitgex Hey man! I have the same problem as you but I have found solution. You need to remove usage of preprocessor string
#if WITH_RUNTIME_PHYSX_COOKING constant within
[https://github.com/Koderz/RuntimeMeshComponent/blob/master/Source/RuntimeMeshComponent/Private/RuntimeMeshComponent.cpp](url), line 1781

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
