### ISSUE TITLE
Get section from static mesh - crash - Blueprint

### ISSUE THREAD

**Issue by electricsauce** [Koderz/RuntimeMeshComponent#59]
Get section from static mesh causes a crash when there is a static mesh applied to the static mesh input. Also, create mesh section causes crash if vert and uv arrays are not the same length (A simple check before creating mesh prevents this)

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
