### ISSUE TITLE
Construction script always generate RuntimeMesh components?

### ISSUE THREAD

**Issue by Tokodboy** [Koderz/RuntimeMeshComponent#60]
Hy.

The question is:

I have a blueprint actor, which is dinamically add runtimemesh components and generate their sections.

The contsruction script is always regenerate the RuntimeMesh component sections each time even so when the section datas and everything else is the same(not changed between 2 compiles)?

The expected behavior is, if I don't change anything in the blueprint actor's variables then it shouldn't  need to regenerate the runtimemesh component's sections.

Only generate it when I edited the bluperint actor in the editor, but after I saved the level with the generated sections and reload the level then I want to use the saved state. The problem is when a level is loaded then the construction script is run and as I can see it regenerate the runtimemesh components too but the previously generation and the new is the same. In this case the runtime mesh component should be recognize that the generation result is the same and shouldn't be executed.

**Comment by Koderz** [comment]
The construction script is something the RMC doesn't directly control. Not sure why you'd get different behavior between the PMC and RMC since neither has direct control over the construction script.  Are you still seeing this behavior?

**Comment by Tokodboy** [comment]
The different behavior between the PMC and RMC that after the construction script generates the meshes I save the level close the editor, run again the editor and load the level. When I use the PMC the level file size is about 400 MB and the loading time is shorter. If I use the RMC the level file size is around 22 MB after saving and the loading time is much more longer.

This is the differences between PMC and RMC what I found.

And I have a question: the RMC will support to copy whole RMCs. I mean that I have a generated RMC  and I want to make a couple of copies based on this RMC.

Thank You your answer.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
