### ISSUE TITLE
Runtime Mesh doesn't render in the Z-EarlyPass

### ISSUE THREAD

**Issue by dustums** [Koderz/RuntimeMeshComponent#62]
When using deferred rendering, Runtime Mesh Components don't render into the Early Z-PrePass  buffer (as shown using RenderDoc).  This means that they don't function well as occluders, which is killing my performance on more complex scenes.  I get a lot of overdraw.  Is this behavior intentional?  Is there a way to force it to be in the Z-PrePass that I don't see?

Btw, the in-engine Procedural Mesh does render into Z-PrePass using deferred rendering.

**Comment by Koderz** [comment]
A super quick check in RenderDoc with just a basic cube and the default material shows it in DPP so not sure why it's not for you. Do you have any weird rendering settings and then the other question is what material you have running?

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
