### ISSUE TITLE
how do i know which section selected under the cursor?

### ISSUE THREAD

**Issue by evehal** [Koderz/RuntimeMeshComponent#63]
is there a way tell me which section selected by mouse?
so i can toggle visibility of section by mouse click

**Comment by Zinglish** [comment]
Do you want this to occur at runtime or during editor?

**Comment by evehal** [comment]
runtime

**Comment by phonne** [comment]
hi dude I also has this problem, can it occur at runtime?

**Comment by Koderz** [comment]
This should in theory work as of a few minutes ago with the source version and 4.17+ using the raytrace tooling but it's untested as of tonight.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
