### ISSUE TITLE
SetMeshSectionVisible not works in 4.16.3

### ISSUE THREAD

**Issue by evehal** [Koderz/RuntimeMeshComponent#64]
SetMeshSectionVisible only works once,for example,section A is visible,then
1:i set section A not visible,SetMeshSectionVisible works
2:i want section A become visible again,SetMeshSectionVisible not works

sometimes SetMeshSectionVisible not works at all

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
