### ISSUE TITLE
bunch of warnings on compile

### ISSUE THREAD

**Issue by devonak** [Koderz/RuntimeMeshComponent#65]
1>d:\gamedesign\koreshanty-4.17\plugins\runtimemeshcomponent_v2.0\source\runtimemeshcomponent\public\RuntimeMeshCore.h(362): warning C4265: 'FRuntimeMeshVertexTypeInfo': class has virtual functions, but destructor is not virtual
1>         instances of this class may not be destructed correctly

**Comment by devonak** [comment]
I can see in the release notes for 4.17 "Compiler warnings for classes with virtual functions but no virtual destructor are now enabled by default."  How can I suppress these warnings?

**Comment by devonak** [comment]
After looking over the marketplace page I can see that people are suggesting the marketplace hasn't processed the plugin update to 4.17?  If this is true can you help me out with how I might migrate it to work on 4.17 on my side?  I just made the jump from 4.15 to 4.17 and it's incredible how much stuff breaks and I depend on this plugin.

**Comment by dc5ala** [comment]
The source hasn't been updated. You can check this pull request for a temporary fix:
https://github.com/Koderz/RuntimeMeshComponent/pull/61/commits/391cb0cbb329dd7d11d5b186120878d585485c20

**Comment by devonak** [comment]
That fix worked on some warnings but I'm still left with 

1>D:\GameDesign\UE_4.17\Engine\Source\Runtime\CoreUObject\Public\UObject/Class.h(989): note: while compiling class template member function 'bool UScriptStruct::TCppStructOps<FRuntimeMeshComponentPrePhysicsTickFunction>::Copy(void *,const void *,int32)'
1>D:\GameDesign\KoreShanty-4.17\Plugins\RuntimeMeshComponent_v2.0\Intermediate\Build\Win64\UE4Editor\Inc\RuntimeMeshComponent\RuntimeMeshComponent.gen.cpp(74): note: see reference to class template instantiation 'UScriptStruct::TCppStructOps<FRuntimeMeshComponentPrePhysicsTickFunction>' being compiled
1>D:\GameDesign\KoreShanty-4.17\Plugins\RuntimeMeshComponent_v2.0\Source\RuntimeMeshComponent\Public\RuntimeMeshComponent.h(69): note: 'FRuntimeMeshComponentPrePhysicsTickFunction &FRuntimeMeshComponentPrePhysicsTickFunction::operator =(const FRuntimeMeshComponentPrePhysicsTickFunction &)': function was implicitly deleted because a base class invokes a deleted or inaccessible function 'FTickFunction &FTickFunction::operator =(const FTickFunction &)

**Comment by Koderz** [comment]
for 4.17 these should be fixed at this point. Will do additional tests with it over the next couple days though. Let me know if you still see any of those.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
