### ISSUE TITLE
UE4 Crash when using "Get section from static mesh" in 4.16.3

### ISSUE THREAD

**Issue by Minakro** [Koderz/RuntimeMeshComponent#66]
All is in the title. there is no way to use that node in 4.16.3

**Comment by rottenhuman** [comment]
I've got the same issue and I blamed myself for using it incorrectly. Was I?

I ended up using Copy Runtime Mesh from Static Mesh Component but now I'm puzzled as to how I can access the geometry data from it. I do need to modify it, after all.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
