### ISSUE TITLE
How to save and load RMC?

### ISSUE THREAD

**Issue by Adiowa** [Koderz/RuntimeMeshComponent#67]
Yes this is not an issue with the code, but we are desperate to know, please, how do you save / load this plugin? It states in the description that it supports it. 
Thank you!

**Comment by CarlitoMurta** [comment]
I'm also having the same problem with TerraNova (https://forums.unrealengine.com/community/released-projects/92958-terra-nova-dynamic-in-game-environment-builder), I want to save my scenario in staticmesh or directly on the disk, I've already created a system where through information of vertices and triangles, I write an .obj file. but until then without success. I hope you can respond to us as soon as possible, it would save my project.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
