### ISSUE TITLE
Lots of warning and errors compiling V2

### ISSUE THREAD

**Issue by BulleTime** [Koderz/RuntimeMeshComponent#68]
Ive downloaded the 'V2' RuntimeMeshComponent_v2.0, when compiling with unreal 4.17 this gives a bunch of erros and warnings, while the master seems to be working okay.

Did i missed anything? is the current Master V2.0?

**Comment by Nazdorovye** [comment]
RMC 2.0 is incompatible with 4.16+

**Comment by BulleTime** [comment]
Seems i actualy have 2.1 !

**Comment by Nazdorovye** [comment]
Thanks for notifying! I also got 2.1 now and it compiles perfectly. )

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
