### ISSUE TITLE
Issues in generating tangent

### ISSUE THREAD

**Issue by YutoToda** [Koderz/RuntimeMeshComponent#69]
Hello.
Because I am not good at English, I am writing this sentence using Google translation.

I am trying to generate a mesh at runtime using "Create Mesh Section".
We prepared Vertices, Triangles, Normals, UV 0 (we got these values ​​from other software), we could display the mesh by using as component input.
However, if you use a bumped texture for that mesh, Bump will flip in some places. (I think that this depends on the value of UV.)

So I first spawned an Actor with RuntimeMesh from Blutility and then saved it as a static mesh from the "Create Static Mesh" button on the detail panel.
We checked "recalculate tangent" from the detail panel of the generated mesh and applied it. Then Bump was displayed correctly.

However, when checking "CalculateNormalTangent" of "Create Mesh Section" or generating Tangents using the "Calculate Tangents for Mesh" component of RMC, Bump did not get correct.
(Also as a side effect, duplicated vertices for hard edges are combined into one and it becomes smooth, which is also a very serious problem)

In my opinion, the method of "recalculating tangent" of UE 4 standard and "Calculate Tangents" of RMC are quite different.
Can we fix this?

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
