### ISSUE TITLE
RMC dont compile on version 4.18

### ISSUE THREAD

**Issue by inferius** [Koderz/RuntimeMeshComponent#70]
Error in compile on:
SelectedObjectsList = DetailBuilder.GetDetailsView()->GetSelectedObjects();

**Comment by dsinglore** [comment]
me too
.GetSelectedObjects   had some error

**Comment by babyinablender** [comment]
I created a patch for this. I'll submit a pull request after I finish fixing the other compilation bugs I'm running into, but for now if you'd like to fix this line, you can change it to:

SelectedObjectsList = DetailBuilder.GetDetailsView().GetSelectedObjects();

**Comment by pushmatrix** [comment]
@the-nerdery-dot-info Any update on a PR? Was this the only line that needed to be changed to make 4.18 work with RMC?

**Comment by TheAse94** [comment]
SelectedObjectsList = DetailBuilder.GetDetailsView()->GetSelectedObjects();

It works for me on 4.18

**Comment by CometGoat** [comment]
Fantastic, this worked for me. The file you need to change is listed in this pull request here: https://github.com/Koderz/RuntimeMeshComponent/pull/71/files

**Comment by CometGoat** [comment]
In case the above link ever changes, it's:
Line 28 in Source/RuntimeMeshComponentEditor/Private/RuntimeMeshComponentDetails.cpp

**Comment by dsinglore** [comment]
emmmm,Build: 2 succeeded, 0 failed.

**Comment by davidthings** [comment]
Since it's not really clear from the above, to compile on 4.18

Line 28 of Source/RuntimeMeshComponentEditor/Private/RuntimeMeshComponentDetails.cpp

Reads:

`SelectedObjectsList = DetailBuilder.GetDetailsView().GetSelectedObjects();`

and it should be

`SelectedObjectsList = DetailBuilder.GetDetailsView()**->**GetSelectedObjects();`

Note the change of operator from '.' to '->'

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
