### ISSUE TITLE
Generation of huge infinite number of File in DerivedDataCache

### ISSUE THREAD

**Issue by ps2invader** [Koderz/RuntimeMeshComponent#73]
Hello,
I notice a problem with this component (Integrate in Spine 2D Runtime) 
When an actor has attached runtime mesh component generate a lot of files called "PHYSX_<alphanumeric string>PHYSXPC_<more text>.udd" inside the Folder DerivedDataCache of engine.

I notice that because on my SSD of 1TB the folder contains 27 milions of this file and a total size of 600gb

Problem is reported on AnswerHub to, here: https://answers.unrealengine.com/questions/669057/proceduralmeshcomponent-creating-files-to-derivedd.html

i made some Screenshot to
![image](https://user-images.githubusercontent.com/2900985/33226578-a09b3218-d191-11e7-8c98-6ca734b4511a.png)
![image](https://user-images.githubusercontent.com/2900985/33226588-c8c5a048-d191-11e7-865c-4eff59f01385.png)

Screenshot made after 20-30 second each other

Work with component settings in editor not fix the problem
Thanks

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
