### ISSUE TITLE
RMC disappears after re-creating it with different VertexBuffer  size?!

### ISSUE THREAD

**Issue by tobias-stein** [Koderz/RuntimeMeshComponent#74]
Hi Folks,
I've got the issue that my RMC disappears after re-creating it with a different Vertex-Buffer size. I could not figure out how to re-create mz RMC with a different sized Buffer. If buffer size stays the same, the RMC updates perfectly. But when I change the buffer size it will disappear.

I am working with the latest version from trunk and UE4.18.

Cheers,
Tobs

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
