### ISSUE TITLE
"show staticmeshes" could not hide runtime mesh

### ISSUE THREAD

**Issue by xoyojank** [Koderz/RuntimeMeshComponent#75]
is there a console command for that?

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
