### ISSUE TITLE
Runtime Mesh in static

### ISSUE THREAD

**Issue by joje1234** [Koderz/RuntimeMeshComponent#76]
Hi! Couldn't find anything in the wiki about how to make runtime mesh render in static pass. How do you set this up?

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
