### ISSUE TITLE
unable to get tessellation working in 4.18

### ISSUE THREAD

**Issue by labdogg1003** [Koderz/RuntimeMeshComponent#77]
I cant seem to get the tessellation to work with any materials that have tessellation on them. furthermore, applying a material with tessellation that is either pn or crack free shows some triangle edges missing in wireframe mode. the attached image is supposed to be a cube built using the rmc create box mesh function.
![cube](https://user-images.githubusercontent.com/8344832/34807244-3f49bba2-f64d-11e7-908a-2f4b7427df30.PNG)

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
