### ISSUE TITLE
engine version 4.16.3 can't compile from source

### ISSUE THREAD

**Issue by mirchd** [Koderz/RuntimeMeshComponent#78]
please help,

RuntimeMeshRendering.h(38): error C2061, "EUpdateFrequency"
RuntimeMeshRendering.h(97): error C2061: "EUpdateFrequency"
RuntimeMeshRendering.h(99): error C2065: “SectionUpdateFrequency” not declare

but #include "RuntimeMeshVersion.h" can find declares

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz

**Comment by mirchd** [comment]
thank you very much,
I'll try it.
