### ISSUE TITLE
OSX Compilation and Crash

### ISSUE THREAD

**Issue by neilmendoza** [Koderz/RuntimeMeshComponent#81]
With UE 4.18 on XCode 9.2 and Version3Dev, I get the following error compiling on OSX...

/BlahBlahBlah/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshCore.h:199:83: error: implicit conversion from 'int' to 'uint16' (aka 'unsigned short') changes value from 65536 to 0 [-Werror,-Wconstant-conversion]

If I change the 65536 to  65535 at line 199 in RuntimeMeshCore.h, it compiles but then crashes the editor. I'm not actually using the component yet. The only thing I did was to include RuntimeMeshComponent.h.

**Comment by Koderz** [comment]
Yeah, that was a mistake. the value was just changed.   That shouldn't be responsible for crashing the editor.   Could you get the stack trace of the crash?

**Comment by neilmendoza** [comment]
FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x10b17799b (filename not found) [in UE4Editor-Core.dylib]
FMacErrorOutputDevice::Serialize(wchar_t const*, ELogVerbosity::Type, FName const&) Address = 0x10cb16c19 (filename not found) [in UE4Editor-ApplicationCore.dylib]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x10b425c9d (filename not found) [in UE4Editor-Core.dylib]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x10b39befb (filename not found) [in UE4Editor-Core.dylib]
FRuntimeMeshNullLockProvider::Lock() Address = 0x1711a8877 (filename not found) [in UE4Editor-RuntimeMeshComponent-3353.dylib]
FRuntimeMeshScopeLock::FRuntimeMeshScopeLock(TUniquePtr<FRuntimeMeshLockProvider, TDefaultDelete<FRuntimeMeshLockProvider> > const&) Address = 0x1711a8b28 [../../../../../neil/Documents/Unreal Projects/GenerativeLand/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshCore.h, line 352] [in UE4Editor-RuntimeMeshComponent-3353.dylib]
operator<<(FArchive&, FRuntimeMeshData&) Address = 0x17113d52c [../../../../../neil/Documents/Unreal Projects/GenerativeLand/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Public/RuntimeMeshData.h, line 1198] [in UE4Editor-RuntimeMeshComponent-3353.dylib]
FAsyncTask<FHotReloadModule::ReplaceReferencesToReconstructedCDOs()::FFindRefTask>::DoWork() Address = 0x122efbe95 (filename not found) [in UE4Editor-HotReload.dylib]
FAsyncTask<FHotReloadModule::ReplaceReferencesToReconstructedCDOs()::FFindRefTask>::DoThreadedWork() Address = 0x122efba0e (filename not found) [in UE4Editor-HotReload.dylib]
FQueuedThread::Run() Address = 0x10b223d18 (filename not found) [in UE4Editor-Core.dylib]
FRunnableThreadPThread::Run() Address = 0x10b20827e (filename not found) [in UE4Editor-Core.dylib]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x10b1b2fc7 (filename not found) [in UE4Editor-Core.dylib]
_pthread_body Address = 0x7fff9e3d393b (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff9e3d3887 (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff9e3d308d (filename not found) [in libsystem_pthread.dylib]

**Comment by Koderz** [comment]
That should actually be fixed in what I pushed a few hours ago. Forgot to come back here and tell you I pushed that

Let me know if that fixed it!

-Koderz

**Comment by neilmendoza** [comment]
First compile didn't crash, so far, so good ;) Thanks!

On an unrelated note, are "ShaderCore", "RenderCore" and "RHI" dependencies still necessary to add to the build file with this new version?

**Comment by Koderz** [comment]
Awesome, hopefully it's fixed!

No, those 3 aren't required for the RMC now. They were required before due to how many parts of the RMC were templated, but that's all changed at this point.
