### ISSUE TITLE
Hotreload crash

### ISSUE THREAD

**Issue by MJLaukala** [Koderz/RuntimeMeshComponent#82]
Happens often when hot reloading:

UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:414]
UE4Editor_RuntimeMeshComponent!operator&lt;&lt;() [g:\mecha\plugins\runtimemeshcomponent\source\runtimemeshcomponent\public\runtimemeshdata.h:1196]
UE4Editor_HotReload!`FHotReloadModule::ReplaceReferencesToReconstructedCDOs&apos;::`2&apos;::FFindRefTask::DoWork() [d:\build\++ue4+release-4.18+compile\sync\engine\source\developer\hotreload\private\hotreload.cpp:1020]
UE4Editor_HotReload!FAsyncTask&lt;`FHotReloadModule::ReplaceReferencesToReconstructedCDOs&apos;::`2&apos;::FFindRefTask&gt;::DoWork() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\public\async\asyncwork.h:264]
UE4Editor_HotReload!FAsyncTask&lt;`FHotReloadModule::ReplaceReferencesToReconstructedCDOs&apos;::`2&apos;::FFindRefTask&gt;::DoThreadedWork() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\public\async\asyncwork.h:288]
UE4Editor_Core!FQueuedThread::Run() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\hal\threadingbase.cpp:451]
UE4Editor_Core!FRunnableThreadWin::Run() [d:\build\++ue4+release-4.18+compile\sync\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:76]

**Comment by Koderz** [comment]
Hey @MJLaukala 

Are you sure you're on the latest version?  I believe this has already been fixed.

**Comment by MJLaukala** [comment]
I'll pull and test the latest when I get home. I'm pretty sure that I was
at the time.

**Comment by MJLaukala** [comment]
It's working now. I was 1 commit behind the fix.

**Comment by Koderz** [comment]
Ok, glad to know that is resolved!
