### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TGMcLean** [Koderz/RuntimeMeshComponent#84]
Failure on build (master):

• MacOS 10.13.1
• VSCode 1.20.1
• Apple LLVM version 9.0.0 (clang-900.0.39.2)
• Target: x86_64-apple-darwin17.2.0
• UE4.18

```
[11/12] Link UE4Editor-RuntimeMeshComponent.dylib
Undefined symbols for architecture x86_64:
  "FRuntimeMeshIndexTraits<unsigned short>::Is32Bit", referenced from:
      URuntimeMeshSlicer::CapMeshSlice(TSharedPtr<FRuntimeMeshData, (ESPMode)1> const&, TSharedPtr<FRuntimeMeshData, (ESPMode)1> const&, TArray<FUtilEdge3D, FDefaultAllocator>&, FPlane, FVector, ERuntimeMeshSlicerCapOption) in Module.RuntimeMeshComponent.cpp.o
ld: symbol(s) not found for architecture x86_64
```

I take it this isn't related to https://github.com/Koderz/RuntimeMeshComponent/issues/50, as this is v3?

And oops, I'm mentioning Clang above, but this is a UBT error, I take it?

Thanks, Koderz.

– TG

**Comment by Koderz** [comment]
Hey @TGMcLean 

That is actually clang related, not UBT.   It should be fixed in the most recent commit, but I can't 100% verify that at the moment. Let me know if that fixes it!

-Koderz

**Comment by TGMcLean** [comment]
That did it, Koderz. Many thanks.

-TG
