### ISSUE TITLE
How to make PhysicsConstraintComponent work with RuntimeMeshComponent?

### ISSUE THREAD

**Issue by ProfFan** [Koderz/RuntimeMeshComponent#85]
Hi Koderz,

I am trying to make a robot in Unreal with RMC, however I cannot make the Physics Constraint Component to work. If I replace all RMCs with Spheres, then PCC works flawlessly. Is there a method to also make it work for RMC?

Thank you in advance!

**Comment by myluoxz** [comment]
Hi Koderz,

RMC v3  support skeletal mesh ？

**Comment by Koderz** [comment]
@ProfFan   This is a known issue, but not sure what causes it. Will be looking into it again soon.

@myluoxz  Nope, it doesn't. That's a complicated thing to support but it's something I've thought about off and on.

**Comment by ProfFan** [comment]
@Koderz Looking forward to it! Also please contact me if you need any help on testing, debuging, etc..

**Comment by hobbeshunter** [comment]
I just run into the same problem. 

@Koderz are you already working on a fix? If not, could you point me to a direction? I may be able to look into this myself.

**Comment by JohnAlcatraz** [comment]
> @Koderz are you already working on a fix? If not, could you point me to a direction? I may be able to look into this myself.

Koderz is no longer working on the RMC, he actually completely disappeared from the internet at the end of last year. So unfortunately you can not expect a reply from him. There is a new community-maintained RMC repo here, which is also 4.22 compatible: https://github.com/Moddingear/RuntimeMeshComponent

This is the new community discord for the RMC: https://discord.gg/PtWQneE

**Comment by hobbeshunter** [comment]
@JohnAlcatraz but the issue still seems to exist, right?

**Comment by JohnAlcatraz** [comment]
@hobbeshunter I do not know, but most likely, yes.

**Comment by hobbeshunter** [comment]
The same problem exists in Procedural Mesh Component. Epic accepted this as a bug. See https://issues.unrealengine.com/issue/UE-75279

Feel free to upvote ;)

**Comment by ProfFan** [comment]
@hobbeshunter I do not think Epic will prioritize with just 3 votes. Are you familiar with tracing or UE4 Physics internals? Maybe we can collaborate and try come up with a fix ourselves.

**Comment by hobbeshunter** [comment]
@ProfFan sadly I'm neither familiar with the UE Physics nor the have I a lot of time. But I can try my best.

**Comment by ProfFan** [comment]
@hobbeshunter If you are working in building a simulator, I am doing kinda the [same](https://github.com/CoreRC/Pavilion), and there is also a group at University of Bremen [who](https://github.com/robcog-iai) is working on this.

**Comment by Koderz** [comment]
Closing as this is for an outdated version of the plugin that's no longer supported.

If you experience this or any other issues in the current version, feel free to report again!

Thanks!
