### ISSUE TITLE
Crash on 4.19 due to change in `FLocalVertexFactory::FDataType`

### ISSUE THREAD

**Issue by pluranium** [Koderz/RuntimeMeshComponent#87]
`FLocalVertexFactory::FDataType` in 4.19 now has a whole bunch of additional members which the current implementation of `RuntimeMeshComponent` leaves uninitialized, leading to a crash. Looks like some calls to `BindPositionVertexBuffer`, `BindTangentVertexBuffer` etc. need to be added in the right places, and possible more involved changes. Is 4.19 something you guys are going to tackle anytime soon?

**Comment by Koderz** [comment]
4.19 is something that will be supported soon. Probably tomorrow if I have time. Been waiting on it to get near release to make sure they don't change stuff like they did last time in 4.18.

**Comment by Koderz** [comment]
What all did you do to even have it run on 4.19? There's 2-3 semi major build issues to even compile it due to changes in the vertexfactory.

**Comment by pluranium** [comment]
Yeah a number of smaller, obvious changes were necessary to get it to build. I got stuck on this one as it requires non-trivial modifications. I can post a PR of what I got so far if it helps.

**Comment by Koderz** [comment]
I have it compiling at this point so probably not much point, but thanks for the offer. Going to have to investigate what they changed in the RHI for 4.19.   The ShaderResourceViews  are something I haven't seen before and I'm not quite sure how to map that onto the RMC's vertex buffers. 

It appears the StaticMesh Rendering now uses 4 independent buffers, {Position}, {Normal/Tangent}, {UVs} {Color}  and each has an associated SRV with their datatype so this might actually cause a problem for the RMC, but I'll look more into it tomorrow.

**Comment by pluranium** [comment]
Yeah I figured it was tricky. Happy to test when you got something.

**Comment by pluranium** [comment]
Hey @Koderz so 4.19 was just released. We're using this plugin on a project and got everything working with 4.19 except for the RuntimeMeshComponent. Let me know if you need any help!

**Comment by dfb** [comment]
Ditto - I'm experiencing what is likely the same crash and will be happy to help test any updates.

**Comment by Koderz** [comment]
I haven't been able to do much towards getting it ready yet. Unfortunately what's needed is going to cause some non-trivial structural changes internally, and also a change in what is the most efficient way to use the RMC.   I still need to research it a bit more, but it looks like what has changed in the engine is going to force the RMC to switch full time to using 4 vertex buffers internally.
1. Position
2. Normal/Tangent
3. UVs (1-8 of them)
4. Color.
This is due to the use of SRVs on the buffers and each of those elements having different datatypes. 

While this is definitely feasible to support, it will mean that single/dual/triple buffer sections will be deprecated out. I'll likely leave their functions in place and just do the necessary conversion internally, but that adds some non-trivial time to updating a section if you feed it a large mesh.   The most efficient way to work with it moving forward is likely to be to use the MeshBuilder which internally can directly read/write the 4 individual buffers. Otherwise you'd end up with something like this...
TArray<FVector> Positions;
TArray<FRuntimeMeshNormalTangent> Tangents;
TArray<FRuntimeMeshUVs> UVs;
TArray<FColor> Colors;

RMC->CreateMeshSection(0, Positions, Tangents, UVs, Colors);

as being the most efficient in terms of copy operations internally, which I don't much like, but might go ahead and support just because it's easy and alongside the meshbuilder is the most efficient way to work with that configuration.

I'm going to try to work on that this week, and I'll try to work on it this weekend, but I leave Sunday for GDC so I doubt I'll have much time over the following week to do much.

I already have all the other known 4.19 issues fixed, this is the big one that I didn't see coming due to not having as much time to stay up to date on what's going on in the UE4 master branch.

So unfortunately as of right now running the RMC on 4.19 isn't possible, and is going to take some work to fix.

**Comment by Koderz** [comment]
There's now a 4.19 branch in this repo. It should fix every compile issue, but is still not usable due to the SRVs not being setup.

**Comment by pluranium** [comment]
Hey Chris any luck so far?

**Comment by Koderz** [comment]
Hey @pluranium 

Unfortunately not a whole lot. At this point I generally know what needs to be done, just haven’t yet had the time to do it. Unfortunately to support it correctly will take a fair ammount of work in the core. I’ll be at GDC this week, so likely won’t have time to really do much until next weekend.

I will say though that I need the RMC on 4.19 for my work, so it will happen, we just had higher priorities for last week and this.

**Comment by JonnyS7G** [comment]
I'm not familiar with how it worked previously, but does this mean that the "Fully configurable vertex structure" feature will no longer be doable?

**Comment by Koderz** [comment]
Yes and no. There’s ways to still mostly support it.  Switching normal/tangent/UV precision is still possible.   Changing between 1 and 8 UVs is also still possible. Outright disabling certain components is a question but that never really worked right anyways.  I’m making progress on full 4.19 support but there’s a lot going on right now after I got back from GDC and GDC took a week itself so it might be another week before I have a full working 4.19 version.

**Comment by badlogic** [comment]
Will the 4.19 supporting version also compile and work against older UE4 versions?

**Comment by mewbits** [comment]
How's the progress on this coming along?

**Comment by christopheKohler** [comment]
Hi all. I'm also looking at compilation under 4.19 and RuntimeMeshComponent is my last problem. Any chance to have a running version on 4.19 soon or any help is needed to acheive the port ?

**Comment by christopheKohler** [comment]
I fixed some issues, but I have two left:

Error	C2512	'FLocalVertexFactory': no appropriate default constructor available	MeshRoomStudio	RuntimeMeshRendering.cpp	130	
Error	C2259	'FRuntimeMeshComponentSceneProxy': cannot instantiate abstract class	MeshRoomStudio	RuntimeMeshComponent.cpp	117

**Comment by Koderz** [comment]
Hey @christopheKohler

There’s a 4.19 branch in this repo which should compile, but it won’t run as there’s some other issues to handle for 4.19.   I’m working through those as I have some time. Hopefully it won’t be too much longer.

**Comment by christopheKohler** [comment]
Thanks, I did not see the branch :) ... It compile fine indeed. Will also test to check if I can help.

**Comment by mewbits** [comment]
Is there a way to get all the files for the plugin with the 4.19 fixes in a zip file?

**Comment by burakcognite** [comment]
Hi @christopheKohler, community will be appreciated if you can create a pr along with your fixes for 4.19 errors 👍

**Comment by mewbits** [comment]
I ended up copying the two folders RuntimeMeshComponent and RuntimeMeshComponentEditor from the source folder to spine-ue4/Plugins/RuntimeMeshComponentPlugin/Source folder. ;)

And it's working so far!

**Comment by burakcognite** [comment]
@Koderz it compiles now but crashes when RMC is being rendered:
D3D11RHI.cpp->InternalSetShaderResourceView->196
Crashes at: const EResourceTransitionAccess CurrentAccess = Resource->GetCurrentGPUAccess();
Resource seems null.

**Comment by Koderz** [comment]
Hey @burakcognite

Yeah that branch only has the compile fixes so I don’t expect it to run yet?

**Comment by kin4n** [comment]
Hello, waiting for 4.19 to try out :) looks like u did an awsome plug, do you think it will get Slice procedural mesh to work faster or Async ?

**Comment by NuclearCookie** [comment]
Also waiting for this. What's your timeline? 
Also check out my open PR. It already helps you with compilation errors and warnings..

**Comment by AngusPei** [comment]
@Koderz @burakcognite 
Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Commands.cpp ->505
FD3D11ShaderResourceView* SRV = ResourceCast(SRVRHI);

SRV is null

Using UnrealEngine-4.19.0-release

**Comment by kin4n** [comment]
any news on this ? (: not pressuring you ... haha

**Comment by pluranium** [comment]
Hey Chris how are things going with the 4.19 version? Do you have an ETA on when you could have it working? We are using it on a commercial project and could allocate an engineer to help you with it if necessary.

**Comment by LiviuChirca** [comment]
@pluranium i believe you should assign someone to fix it or do it yourself as i don't believe this project gets too much attention anymore. Or switch to PMC which is getting updated by Epic. Just saying...

**Comment by Koderz** [comment]
@pluranium  I replied to you directly in email.

In short I'm moving in 2 weeks so the past couple have been busy preparing for that. I definitely haven't abandoned this, just honestly can't prioritize a free component right this minute as much as I like working on it.

**Comment by AngusPei** [comment]
@Koderz shall we develop this program together ?

**Comment by burakcognite** [comment]
Is this somehow related to
https://issues.unrealengine.com/issue/UE-56516
? @Koderz

**Comment by vree4K** [comment]
@Koderz in 2 weeks was 1 weeks ago, abandoned this? feels so.

@pluranium @AngusPei you also still waiting or did you find better alternative?

**Comment by Koderz** [comment]
@vree4K  Might want to read that comment again.  While I like working on this component and still haven't abandoned it, I'm in the tail end of a move. I also said I was moving in 2 weeks, not that I'd be done moving in 2 weeks.  I'm hoping that by next weekend I'll start having more time but it's a longshot right now.    This is a freeware component, so I have to prioritize other things above it right now.

@AngusPei  What are you offering?

@burakcognite  Not exactly. It's just needing to update the RMC structurally to work with the changes made in 4.19

**Comment by pushmatrix** [comment]
@Koderz I'm sure many of us would gladly donate / fund towards the development :)

**Comment by Koderz** [comment]
@pushmatrix 

I have a working version for 4.19 that's not done but the core is working. Hopefully this weekend I'll have the time to finish it up and clean it up.

I thank those who have donated to support this plugin, even in the smallest ways! Unfortunately though for me to truly prioritize it over other projects it'd have to get some far more substantial assistance.

WIth that said I hope to have some more time soon! I do still care about this project!

**Comment by M-Pixel** [comment]
I think this thread is an indication that (especially given Epic's neglect of the issue-ridden ProceduralMeshComponent), the most important thing for this plugin after the 4.19 refactor is documentation and comments for the purpose of empowering community support. The amount of reverse-engineering required for anybody but @Koderz to contribute is a significant barrier to entry.

**Comment by Koderz** [comment]
This should be fixed in the latest version! If this problem persists please feel free to reopen this issue!
