### ISSUE TITLE
Collision doesn't work in packaged build

### ISSUE THREAD

**Issue by prashanthbollam** [Koderz/RuntimeMeshComponent#89]
`NewMesh->CreateMeshSection(m, MeshData->Vertice, MeshData->Faces, MeshData->Normal, MeshData->Textures, MeshData->VertexColor, MeshData->Tangents, true, EUpdateFrequency::Average);`

Collision works in Editor mode, but not in packaged build (Debug game mode).

I am using RuntimeMeshComponent v3.0 with UE4 4.17.2

**Comment by Koderz** [comment]
Hey @prashanthbollam 

Yeah, this is due to an engine bug that I'll probably submit a fix for when I have some time. The easiest way around it is to enable async collision.  I'll also try to find a better workaround here soon. Hopefully that will work for you as a temporary fix.

**Comment by prashanthbollam** [comment]
Hi @Koderz 
I enabled async collision. Collision still doesn't work in packaged build.
This is what I am doing:
```
NewMesh->SetCollisionUseComplexAsSimple(true);
NewMesh->SetCollisionUseAsyncCooking(true);
NewMesh->CreateMeshSection(m, MeshData->Vertice, MeshData->Faces, MeshData->Normal, MeshData->Textures, MeshData->VertexColor, MeshData->Tangents, true, EUpdateFrequency::Infrequent);
```
Is this the correct way to enable async collision?

**Comment by Koderz** [comment]
Hey @prashanthbollam 

Do you have the RuntimePhysXCooking (I think that's the correct name) module added to your build.cs file?

**Comment by prashanthbollam** [comment]
Hi @Koderz ,

Thanks for the reply.

I tried adding the RuntimePhysXCooking module. Still it doesn't work.
This is how I am adding module names. 
`PublicDependencyModuleNames.AddRange(
            new string[] {
                "Core",
                "CoreUObject",
                "Engine",
                "InputCore",
                "ShaderCore",
                "RenderCore",
                "RHI",
                "ProceduralMeshComponent",
                "RuntimeMeshComponent",
                "RuntimePhysXCooking",
                "HeadMountedDisplay",
                "Slate",
                "SlateCore",
                "XmlParser"
            }
        );`
Can you suggest how I can debug this issue ?

Thank you

**Comment by Koderz** [comment]
I haven't heard from you in a while, and I believe this is working correctly except for an engine bug I'll be submitting a fix for soon.  I'll be closing this issue but if you are still having issues, please feel free to reopen it!
