### ISSUE TITLE
4.17.1-release Project wont build with plugin enabled.

### ISSUE THREAD

**Issue by FaceDeskFistScreen** [Koderz/RuntimeMeshComponent#91]
Hello,

The link to v3.0 in the forum post is dead.
https://forums.unrealengine.com/unreal-engine/marketplace/85617-runtime-mesh-component-rendering-high-performance-runtime-generated-meshes
Ive tried v2, 4,19 beta, and what ever version the default master branch is, adding them to the project causes the editor to fail to open. It first prompts to disable the plugin as its not compatible with this version of the engine, clicking no, the editor tries to rebuild the project files and fails. This happens every time until deleting the files from the plugins folder in the project. If theres a version that should work for me let me know. 

Thanks.

**Comment by Koderz** [comment]
I’m not aware of any issues with 4.17.  If you’re referencing it from c++ make sure you get the other modules needed included as well.  They’re on the wiki here but I’m on my phone right now.

**Comment by Koderz** [comment]
I haven't heard from you in a while, and cannot replicate this issue on my end. I'm closing this issue but if you still have problems with it feel free to reopen the issue!
