### ISSUE TITLE
Update 4.19 Runtime error

### ISSUE THREAD

**Issue by AngusPei** [Koderz/RuntimeMeshComponent#93]
Engine\Source\Runtime\Engine\Private\LocalVertexFactory.cpp ->62

![image](https://user-images.githubusercontent.com/4378435/38553162-ecc8027c-3cf0-11e8-9b5e-7f75f959842a.png)

![image](https://user-images.githubusercontent.com/4378435/38553131-db177102-3cf0-11e8-8448-09e749f6fdc7.png)

Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Commands.cpp ->505
FD3D11ShaderResourceView* SRV = ResourceCast(SRVRHI);

SRV is null

Using UnrealEngine-4.19.0-release And  UnrealEngine-4.19.1-release

**Comment by huizuohaode** [comment]
I have the same problems ?

**Comment by sherocyc** [comment]
save problem

**Comment by M-Pixel** [comment]
... or, as it turns out, you can just set the SRV parameters to `nullptr`. I suppose I should have just tried that in the first place.

**Comment by Koderz** [comment]
There's a different issue with more info. I have a working version on 4.19 done correctly and it's far more than just setting them to null, that just causes other issues.  I still have some work to do to fix the full API for it as internally it changed quite a bit.

**Comment by Koderz** [comment]
This should be fixed in the latest version with full 4.19 (and 4.20) support!
