### ISSUE TITLE
What happen to ESectionUpdateFlags::MoveArrays

### ISSUE THREAD

**Issue by wilberolive** [Koderz/RuntimeMeshComponent#94]
I notice that ESectionUpdateFlags::MoveArrays has been commented out in the 3.0 Beta. Is this being removed or is it just temporarily commented out?

**Comment by Koderz** [comment]
It is indeed being removed. Some of the internal structural changes keep this from being possible to really implement. 

Furthermore with the new ability to update the section in place using the meshbuilder and BeginSectionUpdate there's arguably an even faster and lower memory way of handling updates.
