### ISSUE TITLE
4.18 runtime Error, Somethings I ignore?

### ISSUE THREAD

**Issue by GR90** [Koderz/RuntimeMeshComponent#95]
I download the  ZIP for 4.19, and do follow the steps in wiki ,but go wrong like this:
![1525958969 1](https://user-images.githubusercontent.com/19780276/39873498-b048e20c-549d-11e8-9fa9-d367f3fbe8f7.png)

**Comment by Koderz** [comment]
That branch didn't support 4.18 at that time. The current master branch now supports 4.17-4.20. If you continue to see this problem feel free to reopen this issue!
